-- MySQL 8 / MariaDB 10.6+. Apply once to a new database. Never drops existing data.
CREATE TABLE IF NOT EXISTS content_lock (id INT PRIMARY KEY) ENGINE=InnoDB;
INSERT IGNORE INTO content_lock VALUES (1);
CREATE TABLE IF NOT EXISTS categories (
 id VARCHAR(80) PRIMARY KEY, sort_order BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE, slug VARCHAR(190) NOT NULL UNIQUE,
 title VARCHAR(255) NOT NULL, description TEXT NOT NULL, image_url VARCHAR(2048) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS subcategories (
 id VARCHAR(80) PRIMARY KEY, sort_order BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE, category_id VARCHAR(80) NOT NULL,
 slug VARCHAR(190) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL,
 description TEXT NOT NULL, image_url VARCHAR(2048) NOT NULL,
 UNIQUE KEY category_pair (id, category_id),
 FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS products (
 id VARCHAR(80) PRIMARY KEY, sort_order BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE, category_id VARCHAR(80) NOT NULL, subcategory_id VARCHAR(80) NULL,
 slug VARCHAR(190) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, description TEXT NOT NULL,
 image_url VARCHAR(2048) NOT NULL, origin_country VARCHAR(150) NOT NULL,
 price DECIMAL(12,2) NOT NULL, currency CHAR(3) NOT NULL,
 FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
 FOREIGN KEY (subcategory_id, category_id) REFERENCES subcategories(id, category_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS product_images (
 product_id VARCHAR(80) NOT NULL, position INT NOT NULL, url VARCHAR(2048) NOT NULL,
 PRIMARY KEY(product_id, position), FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS settings (
 name VARCHAR(40) PRIMARY KEY, value JSON NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS slides (
 id VARCHAR(80) PRIMARY KEY, position INT NOT NULL, title VARCHAR(255) NOT NULL,
 subtitle TEXT NOT NULL, image_url VARCHAR(2048) NOT NULL, tags JSON NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS social_links (
 platform VARCHAR(30) PRIMARY KEY, label VARCHAR(80) NOT NULL,
 enabled BOOLEAN NOT NULL, url VARCHAR(2048) NOT NULL, position INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS admins (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL DEFAULT 'admin',
 active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS media (
 path VARCHAR(200) PRIMARY KEY, owner_hash CHAR(64) NOT NULL,
 purpose VARCHAR(30) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS submissions (
 id CHAR(32) PRIMARY KEY, kind VARCHAR(30) NOT NULL, payload JSON NOT NULL,
 reference_image VARCHAR(2048) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS rate_limits (
 bucket CHAR(64) PRIMARY KEY, window_start BIGINT NOT NULL, hits INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
